Server.port: 8443

server:
 http2:
  enabled: true
 ssl:
  enabled: true
  key-store: classpath:server.jks
  key-store-type: PKCS12
  key-store-password: secret
  key-alias: localhost
  key-password: secret

management:
 endpoint:
  metrics:
   enabled: true

app:
 jwtSecret: mySecretKey
 jwtExpirationMs: 86400000

spring:
 datasource:
  url: jdbc:postgresql://localhost:5432/bankdb
  username: postgres
  password: root
 jpa:
  properties:
   hibernate:
    jdbc.lob.non_contextual_creation: true
    dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: create
